version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - ecommerce_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=wnsvaf309
      - MYSQL_USER=tkdrb136
      - MYSQL_PASSWORD=wnsvaf309

  product-admin-service:
    image: admin-service:1.0.0
    networks:
      - ecommerce_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=tkdrb136
      - SPRING_DATASOURCE_PASSWORD=wnsvaf309
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  product-delivery-service:
    image: delivery:1.0.0
    networks:
      - ecommerce_network
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=tkdrb136
      - SPRING_DATASOURCE_PASSWORD=wnsvaf309
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      -
  user-service:
    image: demo:1.0.0
    networks:
      - ecommerce_network
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=wnsvaf309
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  ecommerce_network:
    driver: bridge

