FROM gradle:latest as builder
WORKDIR /workspace/app
COPY ./basket /workspace/app/
RUN ./gradlew build -p basket
EXPOSE 8080

ENTRYPOINT ["java","-jar",\
            "basket/build/libs/basket-0.0.1-SNAPSHOT.jar"]