FROM gradle:latest as builder
WORKDIR /workspace/app
COPY . /workspace/app/
RUN .././gradlew build -p admin-service
EXPOSE 8080

ENTRYPOINT ["java","-jar",\
            "admin-service/build/libs/admin-service-0.0.2.jar"]