server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/user/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
              - Path=/admin/**
#          filters:
#            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - AuthorizationHeaderFilter
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
          filters:
            - AuthorizationHeaderFilter
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/coupon/**
          filters:
            - AuthorizationHeaderFilter
        - id: ranking-service
          uri: lb://ranking-service
          predicates:
            - Path=/rank/**




logging:
  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: gateway
    path: C:\logs\gateway\gateway.log
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) ---- [%-10.10thread] %cyan([%logger{0}:%line] %M)  %marker %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ---- [%-10.10thread] [%logger{0}:%line] %M  %marker %msg%n"
  level:
    root: INFO



  #jwt:
  #  secret: securtytest

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: eyJhbGciOiJIUzI1NiJ9.aGVsbG8gd29ybGQ.-aGmFI1PnL6hrGpVCapG31O5FZKeo6K-w09wY-GIh8o
  refresh-token-name: refresh-token
  access-token-name: access-token

## 유레카 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://123.0.0.1:8761/eureka
#      defaultZone: http://0.0.0.0:8761/eureka
