server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
#        - GlobalFilter
      routes:
        - id: user-service
#          uri: http://localhost:8080/
          uri: lb://auth-service
          predicates:
            - Path=/user/**
        - id: admin-service
#          uri: http://localhost:8081/
          uri: lb://admin-service
          predicates:
              - Path=/admin/**
          filters:
            - AuthorizationHeaderFilter


logging:
  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: userLog
    path: C:/logs/gateway
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) ---- [%-10.10thread] %cyan([%logger{0}:%line] %M)  %marker %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ---- [%-10.10thread] [%logger{0}:%line] %M  %marker %msg%n"
  level:
    root: INFO



  #jwt:
  #  secret: securtytest

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: eyJhbGciOiJIUzI1NiJ9.aGVsbG8gd29ybGQ.-aGmFI1PnL6hrGpVCapG31O5FZKeo6K-w09wY-GIh8o
  refresh-token-name: refresh-token
  access-token-name: access-token

# 유레카 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
