redis:
  port: 6379
  host: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: wnsvaf309
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
jwt:
  secret: securtytest


