ARG ELK_VERSION=8.10.2

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:8.10.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu