###################
# Axon config #####
###################
axon:
  serializer:
    general : xstream
  axonserver:
    servers: 127.0.0.1:8124

#app:
#  bootstrapServer: localhost:9092

#kafka:
#  notification:
#    topic: notification