ARG ELK_VERSION=8.10.2

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:8.10.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json