ARG ELK_VERSION=7.10.0

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:7.10.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json