name: Shose -Dev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-access-key-id: ${{secrets.DEV_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2
          
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker images for modules
      run: |
        modules=("admin-service" "basket" "module3" "module4" "module5" "module6" "module7" "module8" "module9" "module10")
        for module in "${modules[@]}"; do
          cd path/to/$module
          docker build -t $REGISTRY/$REPOSITORY:$module-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$module-$IMAGE_TAG
        done
