name: Shose -Dev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-access-key-id: ${{secrets.DEV_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2
          
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build with Gradle
      run: ./gradlew docker

    - name: Build and push Module1 Docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: shoemarket-dev
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd $GITHUB_WORKSPACE/admin-service
        docker build -t $REGISTRY/$REPOSITORY:admin-service-0.0.1 --build-arg JAR_FILE=admin-service.jar .
        docker push $REGISTRY/$REPOSITORY:admin-service-0.0.1
